# Copyright 2023 You-Sheng Yang and others
# SPDX-License-Identifier: FSFAP
# Copying and distribution of this file, with or without modification, are
# permitted in any medium without royalty provided the copyright notice and
# this notice are preserved. This file is offered as-is, without any warranty.
---
name: 'build-image'
description: 'Build component images'
author: 'vicamo'

inputs:
  vendor:
    description: 'Distribution vendor. Currently supports only debian.'
    default: 'debian'
  release:
    description: 'Distribution release name, e.g. unstable for debian.'
    default: 'unstable'
  architectures:
    description: 'Space-separated debian architecture names.'
    default: 'amd64'
  target:
    description: 'Target image stage.'
    required: true
  image_version:
    description: 'Value for org.opencontainers.image.version.'
    required: true
  tag_prefix:
    description: 'String prefix for built image tag.'
    required: true
  ghcr_password:
    required: true

runs:
  using: 'composite'
  steps:
    - name: Transform docker platforms
      id: transform
      shell: bash
      run: |
        native=" $(dpkg --print-architecture) $(dpkg --print-foreign-architectures) "
        archs=(${{ inputs.architectures }})
        platforms=""
        qemu=""
        for arch in "${archs[@]}"; do
          platform=
          case "${arch}" in
            amd64) platform=linux/amd64;;
            i386) platform=linux/386;;
            arm64) platform=linux/arm64/v8;;
            armhf) platform=linux/arm/v7;;
            armel) platform=linux/arm/v5;;
            mips64el) platform=linux/mips64le;;
            riscv64) platform=linux/riscv64;;
            ppc64el) platform=linux/ppc64le;;
            s390x) platform=linux/s390x;;
            *)
              echo "Unsupported arch '${arch}'" >&2
              exit 1
              ;;
          esac

          case "${native}" in
            *" ${arch} "*) ;;
            *) qemu="1";;
          esac

          platforms="${platforms},${platform}"
        done
        platforms="${platforms#,}"
        qemu="${qemu:+true}"

        echo "::group::Outputs"
        echo "platforms=${platforms}" | tee -a "${GITHUB_OUTPUT}"
        echo "qemu=${qemu}" | tee -a "${GITHUB_OUTPUT}"
        echo "::endgroup::"

    -
      # Add support for more platforms with QEMU (optional)
      # https://github.com/docker/setup-qemu-action
      name: Set up QEMU
      uses: docker/setup-qemu-action@v3
      if: steps.transform.outputs.qemu == 'true'
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      with:
        version: v0.12.0
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ inputs.ghcr_password }}

    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v5
      with:
        labels: |
          org.opencontainers.image.description=${{ inputs.target }} image for ${{ inputs.vendor }}:${{ inputs.release }}
          org.opencontainers.image.licenses=FSFAP
          org.opencontainers.image.vendor=${{ github.repository_owner }}
          org.opencontainers.image.version=${{ inputs.image_version }}
        annotations: |
          org.opencontainers.image.description=${{ inputs.target }} image for ${{ inputs.vendor }}:${{ inputs.release }}
          org.opencontainers.image.licenses=FSFAP
          org.opencontainers.image.version=${{ inputs.image_version }}
        images: ghcr.io/${{ github.repository_owner }}/staging
        flavor: |
          latest=false
          prefix=${{ inputs.tag_prefix }}
        tags: |
          ${{ inputs.target }}-${{ inputs.release }}
      env:
        DOCKER_METADATA_ANNOTATIONS_LEVELS: manifest,index

    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: 'images'
        build-args: |
            BASE_IMAGE=${{ inputs.vendor }}:${{ inputs.release }}
            VENDOR=${{ inputs.vendor }}
            RELEASE=${{ inputs.release }}
        labels: ${{ steps.meta.outputs.labels }}
        annotations: ${{ steps.meta.outputs.annotations }}
        no-cache: true
        outputs: type=image,push=true
        platforms: ${{ steps.transform.outputs.platforms }}
        provenance: false
        tags: ${{ steps.meta.outputs.tags }}
        target: ${{ inputs.target }}
