# Copyright 2023 You-Sheng Yang and others
# SPDX-License-Identifier: FSFAP
# Copying and distribution of this file, with or without modification, are
# permitted in any medium without royalty provided the copyright notice and
# this notice are preserved. This file is offered as-is, without any warranty.
---
name: 'clone-test-project'
description: 'Clone Debian grep package for CI tests'
author: 'vicamo'

inputs:
  vendor:
    description: >-
      Specify the distro vendor for the testing project to be cloned.
    required: true
  release:
    description: >-
      Specify the release branch for the testing project to be cloned.
    required: true

outputs:
  source_path:
    description: Full path to the cloned testing project.
    value: ${{ steps.clone.outputs.source_path }}

runs:
  using: 'composite'
  steps:
    - name: Clone debian grep package
      id: clone
      shell: bash
      run: |
        git clone -b "ubuntu/${{ inputs.release }}" \
            https://git.launchpad.net/ubuntu/+source/grep
        { \
          cd grep; \
          git branch --track pristine-tar origin/importer/ubuntu/pristine-tar; \
          cd -; \
        }

        echo "source_path=grep" >> "${GITHUB_OUTPUT}"
